[package]
name = "bevy_proto"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy_proto_derive = { path = "bevy_proto_derive" }
bevy = "0.5"
serde = "1.0.130"
typetag = "0.1"
serde_yaml = "0.8"
dyn-clone = "1.0.4"