[package]
name = "bevy_proto"
version = "0.1.0"
edition = "2018"
authors = ["Gino Valente <gino.valente.code@gmail.com>"]
description = "Create config files for entities in Bevy"
repository = "https://github.com/MrGVSV/bevy_proto"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "archetype", "config", "entity"]
readme = "README.md"
exclude = ["assets/**/*", ".github/**/*"]

[dependencies]
bevy_proto_derive = { version = "0.1.0", path = "bevy_proto_derive" }
bevy = "0.5"
serde = "1.0.130"
typetag = "0.1"
serde_yaml = "0.8"
dyn-clone = "1.0.4"
indexmap = "1.7.0"

[badges]
maintenance = { status = "experimental" }

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "bundles"
path = "examples/bundles.rs"

[[example]]
name = "bench"
path = "examples/bench.rs"