[package]
name = "bevy_proto_derive"
version = "0.1.0"
edition = "2018"
description = "Derive macro for use with bevy_proto"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.32"